### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by isaacdozier** [selftaughtprogrammers/selftaughtprogrammers.github.io#1]
I'm having an issue accessing the remote via Git. From what I understand the default setting has all users set to 'read' and in order to push my local changes to the remote, I need 'write' access. Please correct me if I'm wrong, however, I've never had such trouble setting up a Jekyll site.

Should be able to adjust user settings at: 
https://github.com/selftaughtprogrammers/selftaughtprogrammers.github.io/settings/collaboration

**Comment by MEXdave1997** [comment]
wait, didn't you create this repo though? I mean, because I created the FAQ repo, and am able to read and write to it just fine, even though its in the "organization's collection.

EDIT: also, have you run the command "git add remote origin" + the repo location link? @isaacdozier

**Comment by isaacdozier** [comment]
Yeah, I created the repo. I'm gonna try some things to see if there is something I'm missing. I just find it odd that both the Github website AND my command line (using c9) both direct me to configure my permissions/access rights.

I'll try to post some error messages/screenshots when i can.

**Comment by MEXdave1997** [comment]
Umm, how about trying to remove the repo, and maybe I can create it and add you to the Collabborator's list? @isaacdozier 

EDIT: BTW, I'm also using C9, and I was able to clone the FAQ repo and push/pull just fine. So maybe something went wrong when creating the repo :confused:

**Comment by isaacdozier** [comment]
Alright, I have it figured out. 2-step Auth over HTTPS was causing issues. All good now, I have the site up and running.

**Comment by isaacdozier** [comment]
Alright, I have it figured out. 2-step Auth over HTTPS was causing issues. All good now, I have the site up and running.
