### ISSUE TITLE
Next Steps?

### ISSUE THREAD

**Issue by MEXdave1997** [selftaughtprogrammers/selftaughtprogrammers.github.io#2]
Now that the repo is setup, what are the plans in terms of design/features? 🤔

**Comment by isaacdozier** [comment]
Content is most important right now. Maybe we can implement our FAQ repo as a page?
edit: I'd like to find a way to access the content in the FAQ repo via git or using JavaScript somehow. Since Jekyll uses markdown, it should be no problem displaying the content as seen in the repo Readme.
